### ISSUE TITLE
Event handling doesnt work on label, when markers are used with MarkerClusterer

### ISSUE THREAD

**Issue by jankowskip** [googlemaps/js-markerwithlabel#13]
#### Environment details
```
    "@google/markerclustererplus": "^5.0.4",
    "@googlemaps/markerwithlabel": "^1.0.0",
```

#### Steps to reproduce

  1. Create multiple Marker With label 
  2. Put them in MarkerClusterer
  3. After zooming in labels dont react to click events (marker still react) 

#### Code example

```
    this.markers = someResourceList.map(someResource => {
      const { position } = someResource;

      const marker = new MarkerWithLabel({
        position: { lat: position.latitude, lng: position.longitude },
        map: this.map,
        opacity: 0.9,
        zIndex: 5,
        icon: 'assets/icons/truck.svg',
        labelContent: "<div><span>Label</span></div>",
        labelAnchor: new google.maps.Point(-50, -27),
        labelZIndexOffset: -1,
        labelClass: "google-maps-marker",
      });
      google.maps.event.addListener(marker, "click", function () {
        console.log('test')
      });
      return marker;
    });
    this.markerClusters = new MarkerClusterer(this.map, this.markers, {});
```

**Comment by jpoehnelt** [comment]
I know markerclustererplus has some issues related to the event pane. I wonder if that is the cause.

**Comment by jankowskip** [comment]
Thanks for response @jpoehnelt
Is there any chance that this bug will be resolved any time soon or i should just find workaround ?

**Comment by jpoehnelt** [comment]
this might actually be related to #24 and #25. fix for #25 is in v1.0.1 and fix for #25 is in v1.0.2 when it is published in a few minutes

**Comment by jankowskip** [comment]
Hey, checked and **its working**, thats actually huge! i've seen many major apps using custom labels without clustering, probably due to this bug, so i lot hope and you did it. 

Sadly im getting 2 errors now, one in console: 
<img width="606" alt="Screen Shot 2020-10-30 at 6 55 44 AM" src="https://user-images.githubusercontent.com/12384594/97666170-5ee17480-1a7d-11eb-86f1-b9221f9742a7.png">
One in compiler: 
<img width="1002" alt="Screen Shot 2020-10-30 at 6 57 44 AM" src="https://user-images.githubusercontent.com/12384594/97666130-4cffd180-1a7d-11eb-9d73-3938fd2ffdd3.png">

**Comment by jpoehnelt** [comment]
@jankowskip Please try v1.0.3 with #29.

**Comment by jankowskip** [comment]
@jpoehnelt No worries i did reset api key after posting :) 
Amazing job! Everything works as expected 🥇 
Thank you a lot @jpoehnelt didn't  expect such a quick and great support, you are awesome!
