### ISSUE TITLE
typing mismatch,  js-markerwithlabel is using @types/google.maps instead of @types/googlemaps. 

### ISSUE THREAD

**Issue by iamtharun** [googlemaps/js-markerwithlabel#141]
Getting build error when trying to use js-markerwithlabel package. 

In order to use map typing I am using @types/googlemaps. I wanted to use js-markerwithlabel, but getting build errors.

![image](https://user-images.githubusercontent.com/31502310/111485337-8b600980-875c-11eb-9ce6-0e7c9e8136ba.png)

![image](https://user-images.githubusercontent.com/31502310/111485501-acc0f580-875c-11eb-9494-20d142eff0fa.png)

Platform: Angular

It appears to issue with types mismatch @types/google[dot]maps vs @types/googlemaps

**Comment by jpoehnelt** [comment]
You can use https://www.typescriptlang.org/tsconfig#skipLibCheck.

**Comment by iamtharun** [comment]
Thanks @jpoehnelt, that fixed it.
