### ISSUE TITLE
Breaking changes not documented

### ISSUE THREAD

**Issue by Enchiridion** [googlemaps/js-markerwithlabel#217]
The docs say `Note: There are some breaking changes from @google/markerwithlabel including anchor position. This should be consider a major version bump!` but what the breaking changes are isn't documented.

**Comment by jacobb84** [comment]
I'd love to see this as well. Recently upgraded to fix an issue the old version had with loading google maps in asynchronously, but the label anchor coordinates don't seem to have an effect anymore. Without knowing what changed it's tough to see what I need to update on my side to get it working again.
