### ISSUE TITLE
What is this all about?!

### ISSUE THREAD

**Issue by MrUpsidown** [googlemaps/js-markerwithlabel#272]
Is this really a MarkerWithLabel library? Is it maintained at all? Is it working? Why does the description say _The library creates and manages per-zoom-level clusters for large amounts of markers._ which is the description of a MarkerClusterer lib?

If it's not working/not maintained, I'd suggest you simply delete this repo as people seem confused. And in case you still maintain it, then please provide an appropriate description. Thanks.

**Comment by jpoehnelt** [comment]
Thanks for reporting, but please don't be so hostile.
