### ISSUE TITLE
addDomListener was deprecated  on April 7 2022

### ISSUE THREAD

**Issue by Gotnoname** [googlemaps/js-markerwithlabel#562]
Hi,

Are there any plans on replacing these calls to use standard addEventListeners instead? If so, do you have any ETAs?

Ref: https://developers.google.com/maps/deprecations#googlemapseventadddomlistener_and_googlemapseventadddomlisteneronce_deprecated_on_april_7_2022

**Comment by FlyMaple** [comment]
have any schedule to fix this? so disturbing

**Comment by cbratschi** [comment]
Any chance to get the pull request being reviewed soon?

**Comment by aitella** [comment]
It's more than 4 months after PR was opened. Is there any chance to review and merge it? @amuramoto

**Comment by amuramoto** [comment]
apologies for the delay on this

**Comment by wlius-support3** [comment]
I was wondering if it would be possible to upload the updated version with this fix to the CDN?
